// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shluwoojhaoueyxbbavi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNobHV3b29qaGFvdWV5eGJiYXZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxNjQ3MDEsImV4cCI6MjA1Mzc0MDcwMX0.UXb_xVTTT9A8uwKjhrTavvQsublk4mPGOYW47idQIhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);